### ISSUE TITLE
Koble HTML mot Webservice

### ISSUE THREAD

**Issue by Chrjac** [Chrjac/Bachelor#2]
Få HTML siden til og snakke med Webservice og få returnern Dummydata av no slag.

**Comment by glennbjorlo** [comment]
Fått en aspx side til å snakke med web-serveren. Gjenstår å få en ren html side til å gjøre det samme

**Comment by ingvildkb** [comment]
Får en ren HTML til å sende over/returnere parametere fra webservice. Gjenstår å kunne sende mer data i form av array/XML
